#pragma once

#ifndef PIN_PROTOMATTER_ADDR_0
#define PIN_PROTOMATTER_ADDR_0 A0
#endif
#ifndef PIN_PROTOMATTER_ADDR_1
#define PIN_PROTOMATTER_ADDR_1 A1
#endif
#ifndef PIN_PROTOMATTER_ADDR_2
#define PIN_PROTOMATTER_ADDR_2 A2
#endif
#ifndef PIN_PROTOMATTER_ADDR_3
#define PIN_PROTOMATTER_ADDR_3 A3
#endif
#ifndef PIN_PROTOMATTER_ADDR_4
#define PIN_PROTOMATTER_ADDR_4 A4
#endif

#ifndef PIN_PROTOMATTER_RGB_0
#define PIN_PROTOMATTER_RGB_0 6
#endif
#ifndef PIN_PROTOMATTER_RGB_1
#define PIN_PROTOMATTER_RGB_1 5
#endif
#ifndef PIN_PROTOMATTER_RGB_2
#define PIN_PROTOMATTER_RGB_2 9
#endif
#ifndef PIN_PROTOMATTER_RGB_3
#define PIN_PROTOMATTER_RGB_3 11
#endif
#ifndef PIN_PROTOMATTER_RGB_4
#define PIN_PROTOMATTER_RGB_4 10
#endif
#ifndef PIN_PROTOMATTER_RGB_5
#define PIN_PROTOMATTER_RGB_5 12
#endif

#ifndef PIN_PROTOMATTER_CLOCK
#define PIN_PROTOMATTER_CLOCK 13
#endif
#ifndef PIN_PROTOMATTER_LATCH
#define PIN_PROTOMATTER_LATCH 0
#endif
#ifndef PIN_PROTOMATTER_OE
#define PIN_PROTOMATTER_OE 1
#endif


